# Generated by Django 4.0 on 2022-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_IMG', '0002_alter_picture_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
