# Generated by Django 4.0 on 2022-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_IMG', '0003_rename_img_picture_picture_picture_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
